### ISSUE TITLE
Pixy Firmare

### ISSUE THREAD

**Issue by archishou** [Andrewiski/ControlFreaks_ftc_app#2]
Hi! 
I'm a programmer for team 4997. 
I was having issues uploading your firmware to the pixy2. It says it cannot retrieve the firmware version. 
I also noticed that I had to build some other things on the actual pixy itself. I was wondering if you could help me figure out exactly how I'm supposed to upload the firmware. I'm quite lost.

**Comment by Andrewiski** [comment]
I believe there is new firmware for the pixy2, the firmware posted is for the Pixy 1.  That being said are you using REV or Modern Robotics as Rev can run the unmodified firmware as there is no I2C byte limit on REV like there is on Modern Robotics.  My Teams just moved to REV and just upgraded to Pixy2 but I have been out of town for work the past 45 days and just returned.  I should be able to begin work on our Pixy2 and Rev setup this weekend. I assume you are programming in JAVA and not Blocks, is this correct. I plan to work on Javablocks support as well when I get some free time so more teams can use Pixy.

**Comment by archishou** [comment]
Yeah, we are using the pixy2 along with java. We've been able to get data out of the pixy, but the code I found doesn't seem to give an x and y value for the signature detected. It seems to be a slur of number that don't mean a whole bunch. However, I may be wrong and maybe I'm just reading the data out incorrectly. :)

**Comment by Team14423** [comment]
Hi - adding on to this late, but figured folks here might have answers. We're trying to connect to the Pixy2, but are having trouble. If it's true that you don't need to modify the firmware, how do you do reads in the I2CDeviceSynch without a register? Is there a register value you can send? If you set it to Lego Mode does that allow for registers? Any thoughts appreciated.

**Comment by Andrewiski** [comment]
Pixy2 had my fixes built into it, it’s been to long I can’t remember what I did I am on the road this month and don’t have any code with me. I remember having the same though as you are having but basicI believe you just start reading you don’t send a registry pointer as you just read what it send and every send dumps a full payload

Sent from my iPad

On Dec 20, 2020, at 3:51 PM, Team14423 <notifications@github.com> wrote:

﻿

Hi - adding on to this late, but figured folks here might have answers. We're trying to connect to the Pixy2, but are having trouble. If it's true that you don't need to modify the firmware, how do you do reads in the I2CDeviceSynch without a register? Is there a register value you can send? If you set it to Lego Mode does that allow for registers? Any thoughts appreciated.
